// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpMnltbr970-bP_YioEyUL4dHAELxt1E',
    appId: '1:1039698595981:web:f112541afe3ae8287992c4',
    messagingSenderId: '1039698595981',
    projectId: 'kpop-4bb66',
    authDomain: 'kpop-4bb66.firebaseapp.com',
    storageBucket: 'kpop-4bb66.firebasestorage.app',
    measurementId: 'G-DEJC76EB2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_CAGFjYs_As3JZkph1fp8mW_20JM6Y8',
    appId: '1:1039698595981:android:a40b9aa15008cc977992c4',
    messagingSenderId: '1039698595981',
    projectId: 'kpop-4bb66',
    storageBucket: 'kpop-4bb66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8VqMp8LmrL9cxJ3uExQ1Dz9j6noxfwo4',
    appId: '1:1039698595981:ios:1c32ffb27c8a0b367992c4',
    messagingSenderId: '1039698595981',
    projectId: 'kpop-4bb66',
    storageBucket: 'kpop-4bb66.firebasestorage.app',
    iosClientId: '1039698595981-5nlnj7qktihhb9nl29s2btr1kau3873h.apps.googleusercontent.com',
    iosBundleId: 'com.example.kpop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8VqMp8LmrL9cxJ3uExQ1Dz9j6noxfwo4',
    appId: '1:1039698595981:ios:1c32ffb27c8a0b367992c4',
    messagingSenderId: '1039698595981',
    projectId: 'kpop-4bb66',
    storageBucket: 'kpop-4bb66.firebasestorage.app',
    iosClientId: '1039698595981-5nlnj7qktihhb9nl29s2btr1kau3873h.apps.googleusercontent.com',
    iosBundleId: 'com.example.kpop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSpMnltbr970-bP_YioEyUL4dHAELxt1E',
    appId: '1:1039698595981:web:fd8fad581e45fb9b7992c4',
    messagingSenderId: '1039698595981',
    projectId: 'kpop-4bb66',
    authDomain: 'kpop-4bb66.firebaseapp.com',
    storageBucket: 'kpop-4bb66.firebasestorage.app',
    measurementId: 'G-CJ1YZLSTWF',
  );
}
